GoogleCloudPlatform/alloydb-python-connector

.github/trusted-contribution.yml

Have renovate PRs add tests:run label instead of default kokoro label

chore: configure trusted-contribution labels

---

noxfile.py

Adding steps that check whether setup.py is in a proper format to publish to pypi successfully.

chore: add pypi check to lint

---

.kokoro/requirements.txt

Closes #76  as this is duplicate since dependabot doesn't have access to secrets in test builds.

chore: bump pygments to 2.15.0 in .kokoro

---

.github/workflows/tests.yaml

Have unit tests run on min and max supported versions only.

ci: pare down unit tests

---

.github/workflows/codeql.yaml
.github/workflows/coverage.yaml
.github/workflows/labels.yaml
.github/workflows/lint.yaml
.github/workflows/scorecard.yaml
.github/workflows/tests.yaml

Reverts GoogleCloudPlatform/alloydb-python-connector#104
Looks like checkout action v4 expects node20 which custom runner does not have currently: https://github.com/GoogleCloudPlatform/alloydb-python-connector/actions/runs/6124357195/job/16624319287

chore: Revert "deps: Update actions/checkout action to v4"

---

requirements-test.txt
tests/system/test_asyncpg_direct_connection.py
tests/system/test_native_asyncpg_direct_connection.py
tests/system/test_psycopg2_direct_connection.py
tests/system/test_sqlalchemy_asyncpg_direct_connection.py

Add direct TCP IAM authentication samples for asyncpg driver (SQLAlchemy + native asyncpg). 
Should result in following sample in docs:
`alloydb_sqlalchemy_asyncpg_connect_iam_authn_direct` region tag:
```python
import sqlalchemy
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy import event
import google.auth
from google.auth.credentials import Credentials
from google.auth.transport.requests import Request
credentials, _ = google.auth.default(
scopes=["https://www.googleapis.com/auth/cloud-platform"]
)
def get_authentication_token(credentials: Credentials) -> str:
"""Get OAuth2 access token to be used for IAM database authentication"""
if not credentials.valid:
request = Request()
credentials.refresh(request)
return credentials.token
engine = create_async_engine( …
```

docs: add direct asyncpg IAM authentication tests

---

google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/refresh.py
google/cloud/alloydb/connector/utils.py
tests/unit/mocks.py
tests/unit/test_client.py
tests/unit/test_instance.py
tests/unit/test_refresh.py

Prefer `publicKey` over `pemCSR` in API request body.
Will follow up after this PR with #14 to make key generation async and non-blocking
Closes #110

chore: prefer `publicKey` over `pemCSR` in API

---

google/cloud/alloydb/connector/refresh.py
tests/unit/mocks.py

Port of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/890, updating refresh calculation to use UTC timestamps.

fix: use utcnow() for refresh calculation

---

setup.py

The library is fully typed, so add a marker to allow linters like `mypy` to pick this up as specified in PEP561.

chore: add py.typed marker

---

google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/utils.py
tests/unit/test_client.py
tests/unit/test_instance.py

Added the following changes to the files:
- Added Async Definition to the generate_key() in utils.py
- Added wrap_future for class member declaration in connector.py
Fixes #14

feat: wrap `generate_keys()` in future

---

google/cloud/alloydb/connector/instance.py
tests/unit/test_instance.py

Hi @jackwotherspoon , this is just an initial PR push, I'll be pushing more changes after testing them out. Meanwhile I have added a method for parsing the Instance URI. I got the opportunity to look into the Go Implementation for same issue. I have added the REGEX for the same.
Fixes #184

feat: add support for domain-scoped projects

---

google/cloud/alloydb/connector/refresh.py
tests/unit/mocks.py
tests/unit/test_refresh.py

In Python 3.12 the use of `utcnow()` is deprecated. https://discuss.python.org/t/deprecating-utcnow-and-utcfromtimestamp/26221
This also updates the timestamps from naive timestamps to aware timestamps.

chore: update `utcnow` to `now(timezone.utc)`

---

google/cloud/alloydb/connector/__init__.py
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/refresh.py
noxfile.py
setup.py
tests/system/test_native_asyncpg_direct_connection.py
tests/system/test_psycopg2_direct_connection.py
tests/system/test_sqlalchemy_asyncpg_direct_connection.py
tests/unit/conftest.py
tests/unit/mocks.py
tests/unit/test_connector.py
tests/unit/test_instance.py
tests/unit/test_refresh.py

Switching to `isort` over `flake8-import-order` as it is better to use a sorter then using the sorting check of a linter.

chore: update lint job to use `isort`

---

README.md
google/cloud/alloydb/connector/__init__.py
google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/asyncpg.py
mypy.ini
tests/system/test_asyncpg_connection.py
tests/unit/mocks.py
tests/unit/test_async_connector.py

feat: add support for asyncpg

---

setup.py

Should have added this as part of #199 
This will allow for `pip install "google-cloud-alloydb-connector[asyncpg]"` to work as intended which we showcase in our README.

fix: add asyncpg as optional dep

---

google/cloud/alloydb/connector/async_connector.py
tests/system/test_asyncpg_iam_authn.py
tests/system/test_pg8000_iam_authn.py
tests/unit/test_async_connector.py

Add support of auto IAM authn for `asyncpg` and the `AsyncConnector` through the use of asyncpg allowing a callable for its password field.
In the future this will be updated to use the metadata exchange like the `Connector` class currently does.
Related to #152

feat: add auto IAM authn for `asyncpg`

---

tests/system/test_asyncpg_connection.py

docs: add asyncpg sample usage

---

tests/system/test_asyncpg_connection.py

Currently `import pytest` will show inside of code sample in docs since it is in the region tag. I have tests set to auto-use async if they are an async function so the marking of the test as async is redundant and can be removed.

chore: remove need for pytest in sample

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connector.py
tests/unit/test_client.py

When callers initialize a Connector, they can now provide a space-separated list of custom user agents. This custom user agent will be appended to the existing user agent, e.g.,
alloydb-python-connect/v0.6.0 custom-agent/v1.0.0 other-agent/v2.0.0

feat: add support for a custom user agent

---

README.md
google/cloud/alloydb/connector/__init__.py
google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/exceptions.py
google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/refresh.py
tests/system/test_asyncpg_iam_authn.py
tests/system/test_asyncpg_public_ip.py
tests/system/test_pg8000_connection.py
tests/system/test_pg8000_iam_authn.py
tests/system/test_pg8000_public_ip.py
tests/unit/conftest.py
tests/unit/mocks.py
tests/unit/test_client.py
tests/unit/test_connector.py
tests/unit/test_instance.py
tests/unit/test_refresh.py

Add support to Python Connector for Public IP AlloyDB connections:
Fixes #220
Fixes #222

feat: add support for public IP connections

---

google/cloud/alloydb/connector/connector.py
tests/unit/test_connector.py

Allow `connector.close()` to be called multiple times, which allows for it to be attempted during garbage collection for automatically closing the `Connector`

chore: improve connector.close

---

.github/workflows/lint.yaml
noxfile.py

Update lint build to run using Python 3.12, updating `python setup.py sdist` to use build instead as the command is deprecated as of Python 3.12

chore: bump lint to Python 3.12

---

google/cloud/alloydb/connector/refresh.py
setup.py

In cryptography v42.0.0 the `not_valid_after_utc` field was added to certs. This allows us to pull the aware datetime cert expiry instead of the naive one which is slowly being deprecated.
This will help to remove a deprecation warning that is currently being outputted:
```
alloydb-python-connector/google/cloud/alloydb/connector/refresh.py:99: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
self.expiration = cert_obj.not_valid_after.replace(tzinfo=timezone.utc)
```
Closes #206

chore: use new `not_valid_after_utc` cert field

---

README.md
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/instance.py

We received feedback from customers indicating confusion regarding the usage of `AlloyDB Admin API` in our documentation. To address this, we are updating the API reference to `AlloyDB API`, as recommended in the [official documentation](https://cloud.google.com/alloydb/docs/reference/rest).

docs: Use AlloyDB API for consistency with the official documentation.

---

.flake8
README.md
google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py
tests/system/test_asyncpg_public_ip.py
tests/system/test_pg8000_public_ip.py
tests/unit/test_async_connector.py
tests/unit/test_connector.py

Adding support for `ip_type` as `str` type with options as `"PUBLIC"`, `"PRIVATE"`.
If users want to configure a Connector for a specific IP type they currently need to import `IPTypes` first and then set `ip_type=IPTypes.PUBLIC` in the Connector config or during their call to connect.
```python
from google.cloud.alloydb.connector import IPTypes
```
This is an extra step that is unnecessary and causes friction to users, we should support users passing in the IPTypes enum or string value. This will allow users to not have to import the additional class.
Closes #247

feat: support `ip_type` as str

---

google/cloud/alloydb/connector/client.py

If custom user agent is not of type `str`, do not use it and use default user agent.
Port of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1052

chore: verify custom user agent is type str

---

.github/workflows/tests.yaml
README.md
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/refresh.py
tests/system/test_asyncpg_psc.py
tests/system/test_pg8000_psc.py
tests/unit/mocks.py
tests/unit/test_async_connector.py
tests/unit/test_client.py
tests/unit/test_connector.py
tests/unit/test_instance.py

Add support to Python Connector for PSC connections:
Fixes #290

feat: add support for PSC

---

requirements-test.txt

To guarantee macOS environments will work for the async SQLAlchemy engines (asyncpg usage) we should be installing the `sqlalchemy[asyncio]`  extra dependencies.
Ref: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1

chore: install asyncio version of SQLAlchemy for tests

---

google/cloud/alloydb/connector/connector.py

Remove __del__ destructor for Connector as it seems to be causing timeout errors.
Related to https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1010.

chore: remove destructor from connector.py

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py
tests/unit/test_instance.py

Rename `Instance` to `RefreshAheadCache` to get ready for adding a
`LazyRefreshCache` type in the future. This will improve naming so customers
are not confused by `Instance` not reflecting an AlloyDB instance and instead
being a cache of connection info to connect to an AlloyDB instance.
Port of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1068

refactor: rename Instance to RefreshAheadCache

---

google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connection_info.py
google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/refresh_utils.py
tests/unit/test_connection_info.py
tests/unit/test_instance.py
tests/unit/test_refresh_utils.py

Renaming `RefreshResult` to `ConnectionInfo` to be better aligned
with other Connector libraries.
Aligning file names with that of Cloud SQL Python Connector by splitting
`refresh.py` into `refresh_utils.py` and `connection_info.py`.
Related to #298

refactor: rename RefreshResult to ConnectionInfo

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connection_info.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py
tests/unit/mocks.py
tests/unit/test_async_connector.py
tests/unit/test_connection_info.py
tests/unit/test_instance.py

Refactor of `AlloyDBClient` and `ConnectionInfo` classes.
Added the `get_connection_info` method to the AlloyDBClient.
This method does an immediate refresh and calls the AlloyDB APIs 
to get a fresh `ConnectionInfo`. This allows better encapsulation.
Refactored `ConnectionInfo` to a dataclass and added two new methods;
`create_ssl_context` and `get_preferred_ip`. Moved all SSL/TLS configuration
within `create_ssl_context`. This way ConnectionInfo() prepares all the info
required to connect and then `create_ssl_context` will use the info to establish
the SSL/TLS connection when called from `Connector.connect` at the time of
connection.
Port of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1079 and https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pu …

refactor: update AlloyDBClient and ConnectionInfo classes

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connection_info.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/enums.py
google/cloud/alloydb/connector/instance.py
tests/unit/test_connection_info.py

Moving all shared enums such as `IPTypes` into `enums.py` as lazy
refresh will add another enum to be shared.

refactor: move shared enums to enums.py

---

README.md
google/cloud/alloydb/connector/__init__.py
google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/enums.py
google/cloud/alloydb/connector/lazy.py
tests/system/test_asyncpg_connection.py
tests/system/test_asyncpg_iam_authn.py
tests/system/test_pg8000_connection.py
tests/system/test_pg8000_iam_authn.py
tests/unit/test_lazy.py

Add `refresh_strategy` argument to `Connector()` that allows setting
the strategy to `"lazy"` to use a lazy refresh strategy.
When creating a Connector via `Connector(refresh_strategy="lazy")`,
the connection info and ephemeral certificate will be refreshed only
when the cache certificate has expired. No background tasks run
periodically with this option, making it ideal for use in serverless
environments such as Cloud Run, Cloud Functions, etc, where the
CPU may be throttled.
Usage example:
```python
from google.cloud.alloydb.connector import Connector
with Connector(refresh_strategy="lazy") as connector:
```
Port of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1093
Closes #298

feat: add support for lazy refresh strategy

---

google/cloud/alloydb/connector/connector.py

In heavy usage, there can be cases where the client does not refresh the token but then the token expires prior to the metadata exchange. This commit ensures that the token is always fresh before proceeding to the metadata exchange.
Fixes #346

fix: refresh token prior to metadata exchange

---

README.md
google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/instance.py

Standardize optional debug logging across AlloyDB Connector packages.
To print debug logs for the Python Connector package add the following to your application:
```python
import logging
logging.basicConfig(format="%(asctime)s [%(levelname)s]: %(message)s")
logger = logging.getLogger(name="google.cloud.alloydb.connector")
logger.setLevel(logging.DEBUG)
```
Example of the debug logs produced:
```sh
2024-07-24 17:52:05,231 [DEBUG]: ['projects/my-proj/locations/us-central1/clusters/my-cluster/instances/my-instance']: Refresh strategy is set to background refresh
2024-07-24 17:52:05,231 [DEBUG]: ['projects/my-proj/locations/us-central1/clusters/my-cluster/instances/my-instance']: Connection info added to cache
2024-07-24 17:52:05,231 [DEBUG]: …
```

feat: add standardized debug logging

---

google/cloud/alloydb/connector/instance.py
google/cloud/alloydb/connector/refresh_utils.py
tests/unit/test_refresh_utils.py

`_seconds_until_refresh` which is used for background refresh strategy
(lazy refresh is unaffected!) should not have `now` as a default argument
due to Python only evaluating default arguments once at function definition.
> Python's default arguments are evaluated only once when the function
is defined, not each time the function is called. ([source](https://www.codecademy.com/learn/learn-intermediate-python-3/modules/int-python-function-arguments/cheatsheet))
Problematic code: https://github.com/GoogleCloudPlatform/alloydb-python-connector/blob/14d6b1c291766eddf9110927ad726892a0fe9798/google/cloud/alloydb/connector/refresh_utils.py#L29-L53
Having `now` as a default argument means it is set once and then never
adjusted. So in subsequent calls to `_seconds_until_refresh` the `duration` …

fix: remove default argument `now` from `_seconds_until_refresh` 

---

.github/workflows/tests.yaml

The `auth` step in unit test builds is only needed for Flakybot,
since Flakybot only runs on `push` and `schedule` events we
can skip auth step for all other events.

ci: speed up unit test builds

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connection_info.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/utils.py
requirements.txt
setup.py
tests/unit/conftest.py
tests/unit/mocks.py
tests/unit/test_connection_info.py

Currently we use Python's standard library read and writes which are blocking I/O.
This PR switches to use [aiofiles](https://pypi.org/project/aiofiles/) which is non-blocking approach to
read/write to disk.
Closes #359

feat: use non-blocking disk read/writes

---

.kokoro/release.sh
.kokoro/release/common.cfg

Update the PyPi release token keystore to a new key. It has been rotated again

chore: update keystore to a new key

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connector.py
tests/unit/mocks.py
tests/unit/test_async_connector.py
tests/unit/test_connector.py

This change is analogous to CloudSQL's https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1118.
The `Connector` caches connection info for future connections and schedules refresh operations. For unrecoverable errors, the cache should be invalidated to stop future bad refreshes. The cache should also be invalidated on failed IP lookups. This PR does these things.

feat: invalidate cache on bad connection info and failed IP lookup

---

tests/unit/test_connector.py

This test doesn't need to be async, because it can use the event loop that is generated by `Connector.__init__()` function.

chore: use sync instead of async in test

---

google/cloud/alloydb/connector/client.py
requirements-test.txt
tests/unit/test_client.py

This change is similar to https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1201, except for AlloyDB.
In short, we want to use the AlloyDB API's response body for error messages, because they are more detailed.

feat: improve aiohttp client error messages

---

README.md
setup.py
tests/system/test_asyncpg_connection.py

This change is analogous to CloudSQL's change:
https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1182

feat: support native asyncpg connection pools

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/connection_info.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/static.py
google/cloud/alloydb/connector/types.py
google/cloud/alloydb/connector/utils.py
tests/unit/conftest.py
tests/unit/mocks.py
tests/unit/test_async_connector.py
tests/unit/test_connector.py
tests/unit/test_static.py

This is a port of https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/572 for the AlloyDB Python connector. It allows connecting to a sandbox AlloyDB instance using connection info properties from a JSON file, instead of calling the AlloyDB APIs to get this information (which is done by the internal and lazy caches).
Using a static connection info currently works for the sync client (`pg8000`), but doesn't work for the async client (`asyncpg`). When using the async client, getting timeout errors [here](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connection.py#L2420), due to [ConnectionDoesNotExistError](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connect_utils.py#L962). This is fine for now, as long as we can use the Python connector (using the …

chore: support static connection info

---

noxfile.py
setup.py
tests/unit/test_packaging.py

This change adds the `google.cloud.alloydb` and `google.api_core` packages as dependencies. These packages are required for the `AlloyDBAdminAsyncClient`, which is being added in https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/416.

chore: add dependencies for AlloyDBAdminAsyncClient library

---

google/cloud/alloydb/connector/connector.py

The `driver` arg for `Connector.metadata_exchange` is unused.
This PR removes it.
Most likely this was going to be used as part of `user_agent` but the client
now handles this.

chore: remove unused driver arg from metadata_exchange

---

README.md
tests/system/test_asyncpg_connection.py
tests/system/test_asyncpg_iam_authn.py
tests/system/test_asyncpg_psc.py
tests/system/test_asyncpg_public_ip.py
tests/system/test_pg8000_connection.py
tests/system/test_pg8000_iam_authn.py
tests/system/test_pg8000_psc.py
tests/system/test_pg8000_public_ip.py

This is the AlloyDB change, based on CloudSQL's change: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/

chore: update tests and README to use lambda over getconn func

---

google/cloud/alloydb/connector/async_connector.py
google/cloud/alloydb/connector/client.py
google/cloud/alloydb/connector/connector.py
google/cloud/alloydb/connector/utils.py
mypy.ini
requirements.txt
tests/unit/mocks.py
tests/unit/test_async_connector.py
tests/unit/test_client.py
tests/unit/test_connector.py
tests/unit/test_utils.py

This PR replaces calls to the AlloyDB admin API that use `aiohttp.ClientSession` to use the `google.cloud.alloydb` package's `AlloyDBAdminAsyncClient` instead.
The dependencies for this change were added in https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/428.
Did a performance test of this change by creating a script to create 500 connections. I ran the script twice: when using the `AlloyDBAdminAsyncClient` and when using `aiohttp.ClientSession`. Got similar results:
```
Using AlloyDBAdminAsyncClient:
Elapsed time: 1483.8013787269592 seconds
Using aiohttp.ClientSession:
Elapsed time: 1478.003143787384 seconds
```
Because the performance is very similar, we can use the `AlloyDBAdminAsyncClient`.
In the error case, for example, when passing an invalid instance URI, it …

feat: Replace aiohttp.ClientSession with AlloyDBAdminAsyncClient

---

google/cloud/alloydb/connector/client.py
tests/unit/mocks.py
tests/unit/test_client.py

This is a fix for https://github.com/GoogleCloudPlatform/alloydb-python-connector/issues/435.
The sync connector will use the `AlloyDBAdminClient` with a `grpc` transport, and the async connector will use the `AlloyDBAdminAsyncClient` with a `grpc_asyncio` transport.

fix: Modify AlloyDBClient to use sync transport for sync connector

---

google/cloud/alloydb/connector/connection_info.py

This PR allows the Python connector to support the most secure form of mTLS, which is `verify-full` mode:
https://www.postgresql.org/docs/current/libpq-ssl.html#LIBQ-SSL-CERTIFICATES. In `verify-full` mode, the hostname provided by the client is matched with the AuthProxy server's certificate's SAN field. If it does not match, the connection is rejected.
Previously, for PSC instances, the AuthProxy server certificates contained DNS names with trailing dots in the SAN field. But Python's OpenSSL library does not allow DNS names to contain trailing dots when doing the hostname verification. So we could not support `verify-full` mode.
As of now, all PSC instances that use the AlloyDB Python connector do not have DNS names with trailing dots in the SAN field anymore. So we can support …

fix: support verify-full mode

---

.github/renovate.json5
requirements-test.txt

https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/465 didn't work. It created
https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/467, which wants to update the package to 2.9.10 for Python 3.9 on Darwin. Currently, Python 3.9 on Darwin is using 2.9.9.
So checking if updating the renovate.json file will help. Gemini mentioned this is the approach for this: [here](https://github.com/user-attachments/assets/b9b0cca9-13d1-4617-a759-97c7995305d2). By doing this, we can hopefully prevent renovate-bot from deciding to upgrade psycopg2-binary to version 2.9.10.
Note: For environments that are not using Python 3.9 on Darwin, `requirements-test.txt` is already using 2.9.10. So renovate-bot should only update to 2.9.11 when it becomes released.

chore: prevent renovate-bot from updating psycopg2-binary to 2.9.10

---

pyproject.toml
requirements-test.txt
requirements.txt
tests/unit/test_instance.py

`aiohttp` is not being used anymore. So we can delete it. This PR also fixes `test_instance.py`, because `RefreshAheadCache` takes in a `FakeAlloyDBClient` object instead of an `aiohttp.ClientSession` object.

chore: delete aiohttp dependency

---

google/cloud/alloydbconnector/connection_info.py
tests/unit/test_connection_info.py

getConnectionInfo RPC returns the IP type values as strings. The current approach only checks if the value is None, which is not a valid return type. This PR's change allows checking for None and empty string types.

fix: modify get_preferred_ip to check for empty values
